# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TempDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import math
from random import randint
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import pyqtgraph as pg
from PyQt5.QtGui import QStandardItem, QStandardItemModel
import pandas as pd
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QPixmap


class Ui_TempDetails(object):
    

    def setupUi(self, TempDetails, mainWindow, df: pd.DataFrame):
        self.main_window = mainWindow
        TempDetails.setObjectName("TempDetails")
        TempDetails.resize(1150, 800)

        self.df = df

        self.temp_dialog_close_button = QtWidgets.QPushButton(TempDetails)
        self.temp_dialog_close_button.setGeometry(QtCore.QRect(1000, 700, 121, 31))
        self.temp_dialog_close_button.setObjectName("temp_dialog_close_button")
        self.temp_dialog_close_button.clicked.connect(self.closeWindow)

        self.cutoff_value_label = QtWidgets.QLabel(TempDetails)
        self.cutoff_value_label.setGeometry(QtCore.QRect(70, 720, 170, 51))
        self.cutoff_value_label.setObjectName("cutoff_value_label")
        self.cutoff_value_label.setText("Enter cutoff value:")

        self.cutoff_input = QtWidgets.QLineEdit(TempDetails)
        self.cutoff_input.setValidator(QtGui.QDoubleValidator(0.0,99.99,2))
        self.cutoff_input.setText("35.00")
        self.cutoff_input.setGeometry(QtCore.QRect(70, 720, 250, 50))
        self.cutoff_input.setObjectName("cutoff_input")
        
        self.cutoff_input_button = QtWidgets.QPushButton(TempDetails)
        self.cutoff_input_button.setGeometry(QtCore.QRect(500, 720, 200, 50))
        self.cutoff_input_button.setObjectName("cutoff_input_button")
        self.cutoff_input_button.clicked.connect(self.new_cutoff_value)

        self.tableView = QtWidgets.QTableWidget(TempDetails)
        self.tableView.setGeometry(QtCore.QRect(770, 20, 340, 340))
        self.tableView.setObjectName("temp_table")
        self.last_time = 0
        self.tableView.setColumnCount(3)
        self.tableView.setHorizontalHeaderLabels(["Time (s)", "Max Temp (C)", "Avg Temp (C)"])
        # Create a model for the table
        # self.table_model = QStandardItemModel()
        # self.table_model.setHorizontalHeaderLabels(["Time", "Temperature"])
        # self.tableView.setModel(self.table_model)

        # self.detailed_temp_chart = pg.PlotWidget(TempDetails)
        # self.detailed_temp_chart.setBackground("w")
        # pen = pg.mkPen(color=(255,0,0))
        # self.detailed_temp_chart.setTitle("Temperature vs Time", color="k", size="15pt")
        # styles = {"color": "red", "font-size": "10px"}
        # self.detailed_temp_chart.setLabel("left", "Temperature (°C)", **styles)
        # self.detailed_temp_chart.setLabel("bottom", "Time (min)", **styles)
        # #self.detailed_temp_chart.addLegend()
        # self.detailed_temp_chart.showGrid(x=True, y=True)
        # self.detailed_temp_chart.setYRange(24, 32)
        # # self.detailed_temp_chart = QtWidgets.QScrollArea(TempDetails)
        # self.detailed_temp_chart.setGeometry(QtCore.QRect(20, 20, 720, 380))
        # self.detailed_temp_chart.setObjectName("detailed_temp_chart")

        self.temp_bar_chart = pg.PlotWidget(TempDetails)
        self.bar_chart = pg.BarGraphItem(x=range(1, 8), height=[30,30,30,30,30,30,30], width=0.5, brush="r")
        
        self.temp_bar_chart.addItem(self.bar_chart)
        self.temp_bar_chart.setGeometry(QtCore.QRect(20, 20, 720, 280))
        self.temp_bar_chart.setObjectName("temp_bar_chart")
        styles = {"color": "black", "font-size": "10px"}
        self.temp_bar_chart.setLabel("left", "Temperature (°C)", **styles)
        self.temp_bar_chart.setBackground("w")
        self.temp_bar_chart.setYRange(28,32)

        self.temp_map_display = QtWidgets.QLabel(TempDetails)
        self.temp_map_display.setGeometry(QtCore.QRect(50, 320, 550, 380))
        self.temp_map_display.setObjectName("temp_map_display")
        self.temp_image = QPixmap("heatmap.png")
        self.scaled_temp_image = self.temp_image.scaled(550, 400, QtCore.Qt.KeepAspectRatio)
        self.temp_map_display.setPixmap(self.scaled_temp_image)
        
        # self.time = df['Time'].tolist()
        # self.temperature = df['Temp'].tolist()
        
        # self.temp_line = self.detailed_temp_chart.plot(
        #     self.time,
        #     self.temperature,
        #     name="Temperature Sensor",
        #     pen=pen
        # )

        for index, row in self.df.iterrows():
            time = row["Time"].split(' ')[-1]
            self.update_table_data(time, round(row["Max Temp"], 2), round(row["Avg Temp"], 2))

        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 349))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.detailed_temp_chart.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(TempDetails)
        QtCore.QMetaObject.connectSlotsByName(TempDetails)

    def retranslateUi(self, TempDetails):
        _translate = QtCore.QCoreApplication.translate
        TempDetails.setWindowTitle(_translate("TempDetails", "Dialog"))
        self.temp_dialog_close_button.setText(_translate("TempDetails", "Close"))
        self.cutoff_input_button.setText(_translate("TempDetails", "Change Cutoff"))
        self.cutoff_input.setText(_translate("TempDetails", str(self.main_window.getCutoffValues()[0])))


    def closeWindow(self):
        self.TempDetails.hide()

    def __init__(self, main_window, df: pd.DataFrame):
        super().__init__()
        self.TempDetails = QtWidgets.QDialog()
        self.setupUi(self.TempDetails, main_window, df)
        
        self.TempDetails.show()

    def update_data(self, data: pd.DataFrame):
        #Format time
        time = data["Time"].iloc[-1].split(' ')[-1]

        #Update chart data
        bar_heights = data.iloc[-1].tolist()[5:12]
        self.update_table_data(time, round(data["Max Temp"].iloc[-1], 2), round(data["Avg Temp"].iloc[-1], 2))

        #Redraw chart
        self.temp_bar_chart.clear()
        self.bar_chart = pg.BarGraphItem(x=range(1, 8), height=bar_heights, width=0.5, brush="r")
        self.temp_bar_chart.addItem(self.bar_chart)
        
        self.temp_image = QPixmap("heatmap.png")
        self.scaled_temp_image = self.temp_image.scaled(550, 400, QtCore.Qt.KeepAspectRatio)
        self.temp_map_display.setPixmap(self.scaled_temp_image)
        
        
        #self.temp_display.display(self.temperature[-1])

    def update_table_data(self, time, max_temp, avg_temp):
        self.tableView.setRowCount(self.tableView.rowCount() + 1)
        self.tableView.setItem(self.tableView.rowCount() - 1, 0, QtWidgets.QTableWidgetItem(str(time)))
        self.tableView.setItem(self.tableView.rowCount() - 1, 1, QtWidgets.QTableWidgetItem(str(max_temp)))
        self.tableView.setItem(self.tableView.rowCount() - 1, 2, QtWidgets.QTableWidgetItem(str(avg_temp)))


    def new_cutoff_value(self):
        self.main_window.setTempCutoffValue(self.cutoff_input.text())
    

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    TempDetails = QtWidgets.QDialog()
    emptydf = pd.DataFrame(columns= ["Time", "Temp", "Distance"])
    ui = Ui_TempDetails(emptydf)
    


    sys.exit(app.exec_())